# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'

        document.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads/documents'

        picture.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads/pictures'
