vich_uploader:
    db_driver: orm

    mappings:
        document:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/public/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        picture:
            uri_prefix: /pictures
            upload_destination: '%kernel.project_dir%/public/pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
