vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        document:
            uri_prefix: /uploads/documents
            upload_destination: document.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        picture:
            uri_prefix: /upload/pictures
            upload_destination: picture.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
