controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# redirecting the admin
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true
